whitelist_rules:
- array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace_spacing
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_element_alignment
  - comma_spacing
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_rangeof_comparison_to_nil
  - control_statement
  - custom_rules
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_and_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - generic_type_name
  - identical_operands
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - lower_acl_than_parent
  - mark
  - min_or_max_over_sorted_first_or_last
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - opening_brace_spacing
  - operator_usage_whitespace
  - operator_function_whitespace
  - overridden_methods_call_super
  - pattern_matching_keywords
  - prefixed_top_level_constant
  - private_actions
  - private_outlets
  - private_over_fileprivate
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_calls_to_super
  - protocol_property_accessors_order
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control_rule
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - returning_whitespace
  - shorthand_operator
  - single_test_class
  - statement_position
  - static_operator
  - superfluous_disable_command
  - switch_and_case_statement_alignment
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - vertical_whitespace
  - vertical_whitespace_before_closing_braces
  - vertical_whitespace_after_opening_braces
  - void_return
  - xctest_specific_matcher
  - yoda_condition_rule

excluded:
  - Pods
